"""
CS01 - CV Creation using LLMs
formatter.py: Renders the generated CV content into a clean, professional
DOCX file using python-docx. Layout is ATS-friendly (no tables, no text boxes).
"""

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


# Brand colour used for headings and name
HEADING_COLOR = RGBColor(0x1F, 0x49, 0x7D)
MUTED_COLOR = RGBColor(0x66, 0x66, 0x66)


def format_cv_to_docx(cv_content: dict, output_path: str):
    """
    Build a well-structured DOCX CV from the generated content dict and
    save it to output_path.

    Sections produced (only if data is present):
        Header → Summary → Skills → Experience → Education → Projects → Achievements
    """
    doc = Document()

    # Reduce default page margins for a more standard CV look
    for section in doc.sections:
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)

    # ------------------------------------------------------------------
    # Header: candidate name
    # ------------------------------------------------------------------
    name_para = doc.add_paragraph()
    name_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    name_run = name_para.add_run(cv_content.get("name") or "Your Name")
    name_run.bold = True
    name_run.font.size = Pt(20)
    name_run.font.color.rgb = HEADING_COLOR

    # Contact line
    contact_parts = [
        x for x in [cv_content.get("email"), cv_content.get("phone")] if x
    ]
    if contact_parts:
        c_para = doc.add_paragraph(" | ".join(contact_parts))
        c_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in c_para.runs:
            run.font.size = Pt(10)
            run.font.color.rgb = MUTED_COLOR

    _add_divider(doc)

    # ------------------------------------------------------------------
    # Professional Summary
    # ------------------------------------------------------------------
    if cv_content.get("summary"):
        _section_heading(doc, "PROFESSIONAL SUMMARY")
        p = doc.add_paragraph(cv_content["summary"])
        p.paragraph_format.space_after = Pt(6)

    # ------------------------------------------------------------------
    # Skills
    # ------------------------------------------------------------------
    if cv_content.get("skills_section"):
        _section_heading(doc, "SKILLS")
        p = doc.add_paragraph(cv_content["skills_section"])
        p.paragraph_format.space_after = Pt(6)

    # ------------------------------------------------------------------
    # Experience
    # ------------------------------------------------------------------
    if cv_content.get("experience"):
        _section_heading(doc, "EXPERIENCE")
        for exp in cv_content["experience"]:
            # Role / company / duration on one line
            exp_para = doc.add_paragraph()
            role_run = exp_para.add_run(
                f"{exp.get('title', '')} — {exp.get('company', '')}"
            )
            role_run.bold = True
            role_run.font.size = Pt(11)
            dur_run = exp_para.add_run(f"  |  {exp.get('duration', '')}")
            dur_run.font.size = Pt(10)
            dur_run.font.color.rgb = MUTED_COLOR

            # Enhanced bullet points generated by Ollama
            bullets_text = exp.get("enhanced_bullets", "")
            if bullets_text:
                for line in bullets_text.splitlines():
                    line = line.strip().lstrip("-").strip()
                    if line:
                        b_para = doc.add_paragraph(style="List Bullet")
                        b_para.add_run(line).font.size = Pt(10)
            exp_para.paragraph_format.space_before = Pt(4)

    # ------------------------------------------------------------------
    # Education
    # ------------------------------------------------------------------
    if cv_content.get("education"):
        _section_heading(doc, "EDUCATION")
        for edu in cv_content["education"]:
            e_para = doc.add_paragraph()
            deg_run = e_para.add_run(
                f"{edu.get('degree', '')} — {edu.get('institution', '')}"
            )
            deg_run.bold = True
            yr_run = e_para.add_run(f"  |  {edu.get('year', '')}")
            yr_run.font.color.rgb = MUTED_COLOR
            if edu.get("gpa"):
                e_para.add_run(f"  |  GPA: {edu.get('gpa')}")

    # ------------------------------------------------------------------
    # Projects
    # ------------------------------------------------------------------
    if cv_content.get("projects"):
        _section_heading(doc, "PROJECTS")
        for proj in cv_content["projects"]:
            p_para = doc.add_paragraph()
            p_run = p_para.add_run(proj.get("name", ""))
            p_run.bold = True
            techs = proj.get("technologies", [])
            if techs:
                p_para.add_run(f"  [{', '.join(techs)}]").font.color.rgb = MUTED_COLOR
            if proj.get("description"):
                desc = doc.add_paragraph(proj["description"])
                desc.paragraph_format.left_indent = Inches(0.2)
                desc.paragraph_format.space_after = Pt(4)

    # ------------------------------------------------------------------
    # Achievements
    # ------------------------------------------------------------------
    if cv_content.get("achievements"):
        _section_heading(doc, "ACHIEVEMENTS")
        for ach in cv_content["achievements"]:
            if ach.strip():
                a_para = doc.add_paragraph(style="List Bullet")
                a_para.add_run(ach.strip()).font.size = Pt(10)

    doc.save(output_path)
    print(f"  DOCX saved: {output_path}")


def _section_heading(doc: Document, title: str):
    """Add a bold, coloured section heading followed by a thin rule."""
    para = doc.add_paragraph()
    run = para.add_run(title)
    run.bold = True
    run.font.size = Pt(12)
    run.font.color.rgb = HEADING_COLOR
    para.paragraph_format.space_before = Pt(10)
    para.paragraph_format.space_after = Pt(2)
    _add_divider(doc)


def _add_divider(doc: Document):
    """Add a subtle horizontal line using repeated dash characters."""
    p = doc.add_paragraph("─" * 90)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in p.runs:
        run.font.size = Pt(7)
        run.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(2)
